stages:
  - test
  - deploy

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  AWS_REGION: "us-east-1"
  FLASK_ENV: "production"

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip

test:
  stage: test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python -m unittest discover

deploy:
  stage: deploy
  only:
    - master  # Deploy solo desde la rama master
  script:
    - apt-get install -y awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - aws elasticbeanstalk create-application-version --application-name YourAppName --version-label $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA --source-bundle S3Bucket=your-s3-bucket,S3Key=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA.zip
    - aws elasticbeanstalk update-environment --environment-name YourEnvironmentName --version-label $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
